// ═══════════════════════════════════════════════════════
// AI TOOLS HUB — Data Layer
// ═══════════════════════════════════════════════════════

const categories = [
  { id:'text-writing', name:'Text & Writing', slug:'text-writing', icon:'✍️', color:'#00D4FF', description:'AI-powered writing assistants, content generators, grammar checkers, and text optimization tools that help you write better and faster.' },
  { id:'image-generation', name:'Image Generation', slug:'image-generation', icon:'🎨', color:'#7C3AED', description:'Create stunning visuals, artwork, and designs with AI image generation and editing tools powered by cutting-edge models.' },
  { id:'video-audio', name:'Video & Audio', slug:'video-audio', icon:'🎬', color:'#F472B6', description:'Transform your video and audio content with AI-powered editing, generation, transcription, and enhancement tools.' },
  { id:'code-dev', name:'Code & Dev', slug:'code-dev', icon:'💻', color:'#10B981', description:'Supercharge your development workflow with AI code assistants, debuggers, code review tools, and automated testing platforms.' },
  { id:'productivity', name:'Productivity', slug:'productivity', icon:'⚡', color:'#F59E0B', description:'Boost your efficiency with AI-powered task management, scheduling, note-taking, and workflow automation tools.' },
  { id:'research-data', name:'Research & Data', slug:'research-data', icon:'🔬', color:'#6366F1', description:'Accelerate research and data analysis with AI tools for data mining, visualization, academic research, and insights extraction.' },
  { id:'marketing-seo', name:'Marketing & SEO', slug:'marketing-seo', icon:'📈', color:'#EF4444', description:'Grow your online presence with AI-driven marketing automation, SEO optimization, social media management, and analytics tools.' },
  { id:'chatbots-assistants', name:'Chatbots & Assistants', slug:'chatbots-assistants', icon:'🤖', color:'#14B8A6', description:'Build and deploy intelligent chatbots, virtual assistants, and conversational AI experiences for customer support and beyond.' },
];

const tools = [
  // ─── Text & Writing ───
  { id:'chatgpt', name:'ChatGPT', slug:'chatgpt', description:'Advanced conversational AI for writing, brainstorming, and content creation powered by GPT-4.', longDescription:'ChatGPT by OpenAI is a powerful conversational AI assistant that can help with a wide range of writing tasks. From drafting emails and blog posts to brainstorming creative ideas and debugging code, ChatGPT leverages the latest GPT-4 model to deliver human-like responses. With plugins and browsing capabilities, it can access real-time information and integrate with third-party services.', category:'text-writing', tags:['chatbot','writing','content','GPT-4','conversational'], url:'https://chat.openai.com', pricing:'Freemium', rating:4.8, featured:true, icon:'💬' },
  { id:'jasper', name:'Jasper', slug:'jasper', description:'Enterprise-grade AI content platform for marketing teams to create on-brand content at scale.', longDescription:'Jasper is an AI content platform designed for enterprise marketing teams. It helps create high-quality, on-brand content across multiple channels including blogs, social media, ads, and emails. With brand voice customization, campaign management, and team collaboration features, Jasper streamlines the entire content creation workflow.', category:'text-writing', tags:['marketing','content','enterprise','brand voice'], url:'https://jasper.ai', pricing:'Paid', rating:4.5, featured:true, icon:'📝' },
  { id:'grammarly', name:'Grammarly', slug:'grammarly', description:'AI writing assistant for grammar checking, tone detection, and style improvement across platforms.', longDescription:'Grammarly is an AI-powered writing assistant that helps you write clear, effective, and mistake-free content. Beyond grammar and spelling, Grammarly offers tone detection, clarity suggestions, and style improvements. It integrates with browsers, email clients, word processors, and messaging apps.', category:'text-writing', tags:['grammar','writing','proofreading','tone'], url:'https://grammarly.com', pricing:'Freemium', rating:4.7, featured:false, icon:'✅' },
  { id:'copy-ai', name:'Copy.ai', slug:'copy-ai', description:'AI-powered copywriting tool that generates marketing copy, social posts, and ad creatives in seconds.', longDescription:'Copy.ai uses advanced AI to help marketers, copywriters, and businesses generate high-converting copy. From Facebook ads and product descriptions to email subject lines and blog post outlines, Copy.ai offers 90+ tools and templates. Its workflow automation features let you build end-to-end content pipelines.', category:'text-writing', tags:['copywriting','marketing','ads','social media'], url:'https://copy.ai', pricing:'Freemium', rating:4.3, featured:false, icon:'📋' },
  { id:'writesonic', name:'Writesonic', slug:'writesonic', description:'AI writer that creates SEO-optimized articles, landing pages, and marketing content.', longDescription:'Writesonic is an AI writing platform that specializes in creating SEO-optimized content. It can generate full-length articles, landing page copy, product descriptions, and social media posts.', category:'text-writing', tags:['SEO','articles','landing pages','content'], url:'https://writesonic.com', pricing:'Freemium', rating:4.2, featured:false, icon:'🚀' },
  { id:'quillbot', name:'QuillBot', slug:'quillbot', description:'AI paraphrasing and summarization tool for rewriting content while preserving meaning.', longDescription:'QuillBot is an AI-powered paraphrasing tool that helps you rewrite sentences, paragraphs, and articles while maintaining the original meaning. It offers multiple modes including Standard, Fluency, Formal, Simple, Creative, and Expand.', category:'text-writing', tags:['paraphrasing','summarization','rewriting'], url:'https://quillbot.com', pricing:'Freemium', rating:4.4, featured:false, icon:'🪶' },
  { id:'notion-ai', name:'Notion AI', slug:'notion-ai', description:'Integrated AI assistant within Notion for writing, summarizing, and brainstorming in your workspace.', longDescription:'Notion AI brings artificial intelligence directly into your Notion workspace. It can help draft documents, summarize meeting notes, generate action items, translate content, and brainstorm ideas — all without leaving your existing workflow.', category:'text-writing', tags:['workspace','notes','summarization','productivity'], url:'https://notion.so/product/ai', pricing:'Paid', rating:4.6, featured:false, icon:'📓' },

  // ─── Image Generation ───
  { id:'midjourney', name:'Midjourney', slug:'midjourney', description:'Premier AI art generator creating stunning, photorealistic and artistic images from text prompts.', longDescription:'Midjourney is one of the most popular AI image generation tools, known for its exceptional artistic quality. Operating through Discord, it creates stunning images from text descriptions using advanced diffusion models. Midjourney excels at photorealistic renders, fantasy art, architectural visualization, and abstract concepts.', category:'image-generation', tags:['art','images','creative','diffusion'], url:'https://midjourney.com', pricing:'Paid', rating:4.9, featured:true, icon:'🖼️' },
  { id:'dall-e', name:'DALL·E 3', slug:'dall-e', description:"OpenAI's image generation model creating detailed images from natural language descriptions.", longDescription:'DALL·E 3 by OpenAI represents a major leap in text-to-image generation. Integrated directly into ChatGPT, it understands nuanced prompts and generates highly detailed, accurate images. It excels at rendering text within images, understanding spatial relationships, and following complex multi-element descriptions.', category:'image-generation', tags:['images','OpenAI','text-to-image','creative'], url:'https://openai.com/dall-e-3', pricing:'Freemium', rating:4.7, featured:true, icon:'🎭' },
  { id:'stable-diffusion', name:'Stable Diffusion', slug:'stable-diffusion', description:'Open-source AI image generator with full customization and local deployment capabilities.', longDescription:'Stable Diffusion is an open-source AI image generation model that can be run locally or through cloud services. It offers unmatched customization through LoRA models, ControlNet, and various samplers.', category:'image-generation', tags:['open-source','images','customizable','local'], url:'https://stability.ai', pricing:'Free', rating:4.6, featured:false, icon:'🌀' },
  { id:'canva-ai', name:'Canva AI', slug:'canva-ai', description:'AI-enhanced design platform with Magic Studio for generating and editing visual content.', longDescription:'Canva AI integrates artificial intelligence throughout the popular design platform. Magic Studio includes Magic Design, Magic Write, Magic Edit, Background Remover, and Magic Expand.', category:'image-generation', tags:['design','templates','editing','accessible'], url:'https://canva.com/ai-image-generator', pricing:'Freemium', rating:4.5, featured:false, icon:'🎨' },
  { id:'leonardo-ai', name:'Leonardo.AI', slug:'leonardo-ai', description:'AI image generation platform specializing in game assets, concept art, and creative production.', longDescription:'Leonardo.AI is a creative AI platform that excels at generating game assets, concept art, and production-quality visuals. It offers fine-tuned models for specific art styles and a real-time canvas.', category:'image-generation', tags:['game assets','concept art','creative','3D'], url:'https://leonardo.ai', pricing:'Freemium', rating:4.4, featured:false, icon:'🎮' },
  { id:'adobe-firefly', name:'Adobe Firefly', slug:'adobe-firefly', description:"Adobe's generative AI integrated into Creative Cloud for commercially safe image creation.", longDescription:"Adobe Firefly is Adobe's family of generative AI models designed to be commercially safe for business use. Trained on licensed content, it generates images, text effects, and color variations. Deeply integrated into Photoshop, Illustrator, and other Creative Cloud apps.", category:'image-generation', tags:['Adobe','commercial','design','Creative Cloud'], url:'https://firefly.adobe.com', pricing:'Freemium', rating:4.3, featured:false, icon:'🔥' },
  { id:'remove-bg', name:'Remove.bg', slug:'remove-bg', description:'AI-powered background removal tool that instantly removes image backgrounds with precision.', longDescription:'Remove.bg uses AI to automatically remove backgrounds from images in seconds. It handles complex edges like hair, fur, and transparent objects with high precision.', category:'image-generation', tags:['background removal','editing','e-commerce'], url:'https://remove.bg', pricing:'Freemium', rating:4.5, featured:false, icon:'✂️' },

  // ─── Video & Audio ───
  { id:'runway', name:'Runway', slug:'runway', description:'AI-powered video generation and editing suite with Gen-2 text-to-video capabilities.', longDescription:'Runway is a leading AI-powered creative suite focused on video generation and editing. Its Gen-2 model can generate video from text, images, or video clips. Additional tools include motion tracking, inpainting, color grading, and more.', category:'video-audio', tags:['video','generation','editing','text-to-video'], url:'https://runwayml.com', pricing:'Freemium', rating:4.6, featured:true, icon:'🎥' },
  { id:'descript', name:'Descript', slug:'descript', description:'AI video & podcast editor that lets you edit media by editing text transcripts.', longDescription:'Descript revolutionizes video and podcast editing by letting you edit media as easily as editing a document. Its AI transcribes audio/video, then you edit the transcript to edit the media.', category:'video-audio', tags:['video editing','podcast','transcription','audio'], url:'https://descript.com', pricing:'Freemium', rating:4.5, featured:false, icon:'🎙️' },
  { id:'elevenlabs', name:'ElevenLabs', slug:'elevenlabs', description:'Hyper-realistic AI voice synthesis and cloning for content creation and dubbing.', longDescription:'ElevenLabs offers the most realistic AI voice generation technology available. It can clone voices with just minutes of audio, generate speech in 29 languages, and create emotionally expressive narration.', category:'video-audio', tags:['voice','text-to-speech','cloning','audio'], url:'https://elevenlabs.io', pricing:'Freemium', rating:4.7, featured:true, icon:'🔊' },
  { id:'synthesia', name:'Synthesia', slug:'synthesia', description:'AI video generation platform creating professional videos with lifelike AI avatars.', longDescription:'Synthesia enables anyone to create professional-quality videos using AI avatars. Choose from 150+ diverse AI presenters, type your script, and generate a video in minutes. Supports 120+ languages.', category:'video-audio', tags:['video generation','avatars','training','enterprise'], url:'https://synthesia.io', pricing:'Paid', rating:4.4, featured:false, icon:'👤' },
  { id:'opus-clip', name:'Opus Clip', slug:'opus-clip', description:'AI-powered tool that turns long videos into viral short clips for social media.', longDescription:'Opus Clip uses AI to analyze long-form videos and automatically extract the most engaging moments as short-form clips for TikTok, Instagram Reels, and YouTube Shorts.', category:'video-audio', tags:['short-form','social media','clips','repurposing'], url:'https://opus.pro', pricing:'Freemium', rating:4.3, featured:false, icon:'✂️' },
  { id:'murf-ai', name:'Murf AI', slug:'murf-ai', description:'AI voice generator with 120+ natural-sounding voices for voiceovers and presentations.', longDescription:'Murf AI provides a large library of realistic AI voices for creating professional voiceovers with 120+ voices across 20+ languages.', category:'video-audio', tags:['voiceover','text-to-speech','e-learning'], url:'https://murf.ai', pricing:'Freemium', rating:4.2, featured:false, icon:'🎤' },

  // ─── Code & Dev ───
  { id:'github-copilot', name:'GitHub Copilot', slug:'github-copilot', description:'AI pair programmer that suggests code completions and entire functions in your editor.', longDescription:'GitHub Copilot is an AI-powered code completion tool that integrates directly into your IDE. Powered by OpenAI Codex, it suggests whole lines, functions, and even complex algorithms based on context and comments.', category:'code-dev', tags:['code completion','IDE','pair programming','GitHub'], url:'https://github.com/features/copilot', pricing:'Paid', rating:4.7, featured:true, icon:'🐙' },
  { id:'cursor', name:'Cursor', slug:'cursor', description:'AI-first code editor built for pair programming with advanced AI models.', longDescription:'Cursor is a next-generation code editor built from the ground up for AI-assisted development. Based on VS Code, it offers deep AI integration including multi-file editing and codebase-aware suggestions.', category:'code-dev', tags:['editor','AI-first','pair programming','VS Code'], url:'https://cursor.sh', pricing:'Freemium', rating:4.8, featured:true, icon:'⚡' },
  { id:'replit', name:'Replit', slug:'replit', description:'Cloud IDE with AI-powered coding, deployment, and collaboration in the browser.', longDescription:'Replit is a cloud-based development platform with built-in AI assistance. Replit AI can generate, explain, debug, and transform code directly in the browser.', category:'code-dev', tags:['cloud IDE','collaboration','deployment','browser'], url:'https://replit.com', pricing:'Freemium', rating:4.4, featured:false, icon:'💡' },
  { id:'tabnine', name:'Tabnine', slug:'tabnine', description:'Privacy-focused AI code assistant with whole-line and full-function completions.', longDescription:'Tabnine is an AI code completion tool that prioritizes privacy and security. It can run locally or in the cloud, supporting 30+ languages.', category:'code-dev', tags:['code completion','privacy','local','enterprise'], url:'https://tabnine.com', pricing:'Freemium', rating:4.2, featured:false, icon:'🔒' },
  { id:'codeium', name:'Codeium', slug:'codeium', description:'Free AI code acceleration toolkit with autocomplete, search, and chat for developers.', longDescription:'Codeium offers a free AI-powered code acceleration toolkit that includes intelligent autocomplete and natural language code search. It supports 70+ programming languages.', category:'code-dev', tags:['free','autocomplete','search','multi-language'], url:'https://codeium.com', pricing:'Free', rating:4.5, featured:false, icon:'🆓' },
  { id:'v0-dev', name:'v0 by Vercel', slug:'v0-dev', description:'AI-powered UI generation tool that creates React components from text descriptions.', longDescription:'v0 by Vercel is an AI-powered UI generation tool that transforms text descriptions and screenshots into production-ready React code.', category:'code-dev', tags:['UI generation','React','prototyping','Vercel'], url:'https://v0.dev', pricing:'Freemium', rating:4.6, featured:false, icon:'🎯' },

  // ─── Productivity ───
  { id:'otter-ai', name:'Otter.ai', slug:'otter-ai', description:'AI meeting assistant that records, transcribes, and summarizes meetings in real-time.', longDescription:'Otter.ai is an AI-powered meeting assistant that automatically records, transcribes, and summarizes your meetings. It integrates with Zoom, Google Meet, and Microsoft Teams.', category:'productivity', tags:['meetings','transcription','notes','collaboration'], url:'https://otter.ai', pricing:'Freemium', rating:4.4, featured:false, icon:'🦦' },
  { id:'zapier-ai', name:'Zapier AI', slug:'zapier-ai', description:'AI-enhanced workflow automation connecting 6,000+ apps with intelligent triggers and actions.', longDescription:'Zapier AI enhances the popular automation platform with artificial intelligence. Create complex workflows using simple English descriptions.', category:'productivity', tags:['automation','workflows','integration','no-code'], url:'https://zapier.com/ai', pricing:'Freemium', rating:4.5, featured:false, icon:'⚙️' },
  { id:'reclaim-ai', name:'Reclaim.ai', slug:'reclaim-ai', description:'AI scheduling assistant that automatically finds the best time for tasks, habits, and meetings.', longDescription:'Reclaim.ai is an AI-powered scheduling tool that automatically organizes your calendar for optimal productivity.', category:'productivity', tags:['scheduling','calendar','time management','habits'], url:'https://reclaim.ai', pricing:'Freemium', rating:4.3, featured:false, icon:'📅' },
  { id:'mem-ai', name:'Mem', slug:'mem-ai', description:'AI-powered knowledge base that self-organizes your notes, docs, and information.', longDescription:'Mem is an AI-first knowledge management tool that automatically organizes your notes and information using AI to surface relevant notes and create connections.', category:'productivity', tags:['notes','knowledge base','organization','AI-first'], url:'https://mem.ai', pricing:'Freemium', rating:4.1, featured:false, icon:'🧠' },
  { id:'todoist-ai', name:'Todoist AI', slug:'todoist-ai', description:'Smart task management with AI-powered task creation, scheduling, and prioritization.', longDescription:'Todoist integrates AI to supercharge task management with smart task breakdown, date suggestions, and priority recommendations.', category:'productivity', tags:['tasks','project management','organization','planning'], url:'https://todoist.com', pricing:'Freemium', rating:4.5, featured:false, icon:'✔️' },
  { id:'clockwise', name:'Clockwise', slug:'clockwise', description:'AI calendar optimization tool that creates focus time and resolves scheduling conflicts.', longDescription:'Clockwise uses AI to optimize your team\'s calendars for maximum focus time, automatically moving flexible meetings to create uninterrupted blocks.', category:'productivity', tags:['calendar','focus time','team','optimization'], url:'https://clockwise.com', pricing:'Freemium', rating:4.2, featured:false, icon:'🕐' },

  // ─── Research & Data ───
  { id:'perplexity', name:'Perplexity AI', slug:'perplexity', description:'AI-powered search engine that provides cited, comprehensive answers to complex questions.', longDescription:'Perplexity AI is an AI-powered answer engine that provides comprehensive, cited responses to your questions. Unlike traditional search engines, it synthesizes information from multiple sources.', category:'research-data', tags:['search','research','citations','answers'], url:'https://perplexity.ai', pricing:'Freemium', rating:4.7, featured:true, icon:'🔍' },
  { id:'elicit', name:'Elicit', slug:'elicit', description:'AI research assistant that finds, summarizes, and extracts data from academic papers.', longDescription:'Elicit is an AI research assistant designed for academic and scientific research, searching through millions of papers and extracting key findings.', category:'research-data', tags:['academic','papers','systematic review','literature'], url:'https://elicit.com', pricing:'Freemium', rating:4.5, featured:false, icon:'📚' },
  { id:'consensus', name:'Consensus', slug:'consensus', description:'AI search engine for scientific research that extracts findings from peer-reviewed papers.', longDescription:'Consensus is an AI-powered search engine built specifically for scientific research, using AI to extract and synthesize key findings from peer-reviewed papers.', category:'research-data', tags:['science','peer review','evidence','meta-analysis'], url:'https://consensus.app', pricing:'Freemium', rating:4.3, featured:false, icon:'🎓' },
  { id:'julius-ai', name:'Julius AI', slug:'julius-ai', description:'AI data analyst that helps you analyze data, create visualizations, and generate insights.', longDescription:'Julius AI is a data analysis platform that lets you analyze complex datasets using natural language. Upload spreadsheets and ask questions in plain English.', category:'research-data', tags:['data analysis','visualization','statistics','spreadsheets'], url:'https://julius.ai', pricing:'Freemium', rating:4.4, featured:false, icon:'📊' },
  { id:'notebook-lm', name:'NotebookLM', slug:'notebook-lm', description:"Google's AI research notebook that analyzes your documents and generates insights.", longDescription:'NotebookLM by Google is an AI-powered research notebook that lets you upload documents and have AI-driven conversations about them. Features Audio Overviews and source-grounded answers.', category:'research-data', tags:['Google','documents','analysis','notebook'], url:'https://notebooklm.google', pricing:'Free', rating:4.6, featured:true, icon:'📔' },
  { id:'scite', name:'Scite.ai', slug:'scite', description:'AI citation analysis tool that shows how papers have been cited — supporting or contrasting.', longDescription:'Scite.ai uses AI to analyze citations in context, showing whether a paper has been supported, contradicted, or just mentioned by subsequent research.', category:'research-data', tags:['citations','academic','analysis','reliability'], url:'https://scite.ai', pricing:'Paid', rating:4.2, featured:false, icon:'🔖' },

  // ─── Marketing & SEO ───
  { id:'surfer-seo', name:'Surfer SEO', slug:'surfer-seo', description:'AI-powered SEO tool that helps create optimized content with real-time scoring and suggestions.', longDescription:'Surfer SEO combines AI with data-driven SEO optimization. Its Content Editor provides real-time optimization suggestions while you write.', category:'marketing-seo', tags:['SEO','content optimization','keywords','rankings'], url:'https://surferseo.com', pricing:'Paid', rating:4.5, featured:false, icon:'🏄' },
  { id:'semrush-ai', name:'Semrush AI', slug:'semrush-ai', description:'Comprehensive marketing platform with AI-powered SEO, content, and competitive analysis.', longDescription:'Semrush integrates AI throughout its comprehensive digital marketing platform with SEO Writing Assistant, ContentShake AI, and smart competitive analysis.', category:'marketing-seo', tags:['SEO','competitive analysis','marketing','keywords'], url:'https://semrush.com', pricing:'Paid', rating:4.6, featured:true, icon:'📊' },
  { id:'hootsuite-ai', name:'Hootsuite AI', slug:'hootsuite-ai', description:'AI-enhanced social media management with auto-generated captions and optimal posting times.', longDescription:'Hootsuite leverages AI to streamline social media management with OwlyWriter AI for generating captions and AI-powered analytics.', category:'marketing-seo', tags:['social media','scheduling','analytics','automation'], url:'https://hootsuite.com', pricing:'Paid', rating:4.2, featured:false, icon:'🦉' },
  { id:'hubspot-ai', name:'HubSpot AI', slug:'hubspot-ai', description:'AI-powered CRM and marketing automation with content generation and lead scoring.', longDescription:'HubSpot integrates AI across its CRM, marketing, sales, and service platform with content generation, predictive lead scoring, and conversation intelligence.', category:'marketing-seo', tags:['CRM','automation','lead scoring','inbound'], url:'https://hubspot.com/artificial-intelligence', pricing:'Freemium', rating:4.4, featured:false, icon:'🧲' },
  { id:'brand24', name:'Brand24', slug:'brand24', description:'AI media monitoring tool that tracks brand mentions and analyzes sentiment across the web.', longDescription:'Brand24 uses AI to monitor your brand mentions across social media, news, blogs, forums, and the web with sentiment analysis and anomaly detection.', category:'marketing-seo', tags:['monitoring','sentiment','brand','social listening'], url:'https://brand24.com', pricing:'Paid', rating:4.3, featured:false, icon:'👁️' },
  { id:'mailchimp-ai', name:'Mailchimp AI', slug:'mailchimp-ai', description:'AI-powered email marketing with smart content generation, segmentation, and send time optimization.', longDescription:'Mailchimp integrates AI throughout its email marketing platform with AI-generated content, subject line optimization, and smart audience segmentation.', category:'marketing-seo', tags:['email','segmentation','optimization','campaigns'], url:'https://mailchimp.com', pricing:'Freemium', rating:4.3, featured:false, icon:'📧' },

  // ─── Chatbots & Assistants ───
  { id:'claude', name:'Claude', slug:'claude', description:"Anthropic's AI assistant known for nuanced understanding, safety, and long-context analysis.", longDescription:'Claude by Anthropic is an AI assistant designed for safety and helpfulness. Known for nuanced understanding, thoughtful analysis, and reduced hallucination. Claude 3.5 Sonnet offers a 200K context window.', category:'chatbots-assistants', tags:['assistant','safety','reasoning','Anthropic'], url:'https://claude.ai', pricing:'Freemium', rating:4.8, featured:true, icon:'🟠' },
  { id:'gemini', name:'Google Gemini', slug:'gemini', description:"Google's multimodal AI assistant with web search, image analysis, and Google ecosystem integration.", longDescription:'Google Gemini is Google\'s multimodal AI assistant powered by the Gemini family of models. It can understand and generate text, code, images, and audio with deep Google integration.', category:'chatbots-assistants', tags:['multimodal','Google','search','assistant'], url:'https://gemini.google.com', pricing:'Freemium', rating:4.5, featured:true, icon:'✨' },
  { id:'poe', name:'Poe', slug:'poe', description:'Multi-bot platform by Quora giving access to ChatGPT, Claude, Gemini, and custom bots.', longDescription:'Poe by Quora provides access to multiple AI chatbots in one place. Users can chat with GPT-4, Claude, Gemini, Llama, and many other models.', category:'chatbots-assistants', tags:['multi-model','platform','custom bots','comparison'], url:'https://poe.com', pricing:'Freemium', rating:4.3, featured:false, icon:'🤝' },
  { id:'character-ai', name:'Character.AI', slug:'character-ai', description:'Create and chat with AI characters — from historical figures to fictional companions.', longDescription:'Character.AI lets users create and interact with AI characters that have distinct personalities and knowledge. Popular for creative writing, role-playing, and language learning.', category:'chatbots-assistants', tags:['characters','roleplay','entertainment','creative'], url:'https://character.ai', pricing:'Freemium', rating:4.4, featured:false, icon:'🎭' },
  { id:'intercom-fin', name:'Intercom Fin', slug:'intercom-fin', description:'Enterprise AI customer service agent that resolves support queries with human-like accuracy.', longDescription:'Intercom Fin is an AI-powered customer service agent designed for enterprise support teams, using your help center and documentation to resolve queries accurately.', category:'chatbots-assistants', tags:['customer service','support','enterprise','automation'], url:'https://intercom.com/fin', pricing:'Paid', rating:4.5, featured:false, icon:'💬' },
  { id:'botpress', name:'Botpress', slug:'botpress', description:'Open-source platform for building AI-powered chatbots with visual flow builder and LLM integration.', longDescription:'Botpress is a leading open-source platform for building conversational AI chatbots with a visual flow builder and seamless LLM integration.', category:'chatbots-assistants', tags:['open-source','chatbot builder','NLU','multi-channel'], url:'https://botpress.com', pricing:'Freemium', rating:4.2, featured:false, icon:'🏗️' },
];

// ─── Helper Functions ───
function getCategoryById(id) { return categories.find(c => c.id === id); }
function getCategoryBySlug(slug) { return categories.find(c => c.slug === slug); }
function getToolBySlug(slug) { return tools.find(t => t.slug === slug); }
function getToolsByCategory(catId) { return tools.filter(t => t.category === catId); }
function getFeaturedTools() { return tools.filter(t => t.featured); }
function searchTools(query) {
  const q = query.toLowerCase();
  return tools.filter(t =>
    t.name.toLowerCase().includes(q) ||
    t.description.toLowerCase().includes(q) ||
    t.tags.some(tag => tag.toLowerCase().includes(q)) ||
    t.category.toLowerCase().includes(q)
  );
}
